name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/123.jpg
  fonts:
    - family: Edu
      fonts:
        - asset: fonts/EduAUVICWANTHand-Bold.ttf
        - asset: fonts/EduAUVICWANTHand-Medium.ttf
        - asset: fonts/EduAUVICWANTHand-Regular.ttf
        - asset: fonts/EduAUVICWANTHand-SemiBold.ttf


