name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.39
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/123.jpg
    - assets/
    - assets/images/forest.jpeg
    - assets/images/night.jpeg
    - assets/images/ocean.jpeg
    - assets/images/waterfall.jpeg
    - assets/images/wind.jpeg
    - assets/audio/forest.mp3
    - assets/audio/night.mp3
    - assets/audio/ocean.mp3
    - assets/audio/waterfall.mp3
    - assets/audio/wind.mp3
    - assets/images/cards/
    - .env
  fonts:
    - family: Edu
      fonts:
        - asset: fonts/EduAUVICWANTHand-Bold.ttf
        - asset: fonts/EduAUVICWANTHand-Medium.ttf
        - asset: fonts/EduAUVICWANTHand-Regular.ttf
        - asset: fonts/EduAUVICWANTHand-SemiBold.ttf


